"""harness-kit init: Generate harness files into a target project."""

from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

console = Console()

# --- Template content -----------------------------------------------------------

AGENTS_MD_STANDARD = """\
# HARNESS.md

{project_description}

Tech stack: {tech_stack}

## Commands

| Action | Command |
|--------|---------|
| Install | `{install_cmd}` |
| Dev server | `{dev_cmd}` |
| Test | `{test_cmd}` |
| Lint | `{lint_cmd}` |
| Type check | `{typecheck_cmd}` |

## Architecture

{architecture}

**Dependency rules**: UI → Services → Data (never reverse).

For full architecture docs, see `docs/ARCHITECTURE.md`.

## Agent Pitfalls (Error-Driven)

<!-- DO NOT pre-fill this section.
     Start empty. Add one line each time you observe the agent making a mistake.
     Example entries (replace with real observations):
     - Do NOT use yarn — this project uses {pkg_manager}
     - Tests in src/legacy/ don't exist. Don't try to run them.
-->

## What Does NOT Exist

<!-- List things the agent commonly looks for but don't exist in your project.
     Example entries (replace with your own):
     - No docker-compose.yml. The app runs directly on the host.
-->

## Verification Checklist

After modifying code, run in this order:
1. `{lint_cmd}` — zero errors
2. `{test_cmd}` — all tests pass
3. `{typecheck_cmd}` — no type errors
"""

CLAUDE_MD_TEMPLATE = """\
# CLAUDE.md

@HARNESS.md

## Claude Code Configuration

### Workflow
- Do NOT auto-commit or push without explicit user confirmation
- When compacting, preserve the full list of modified files

### Model Preferences
- Use Sonnet for routine tasks
- Use Opus for architecture decisions and complex analysis
"""

KIRO_PRODUCT_TEMPLATE = """\
---
inclusion: always
---
# Product Context

## What is this project?
{project_description}

## Target Users
<!-- Describe who uses this product -->

## Key Features
<!-- List main features -->
"""

KIRO_TECH_TEMPLATE = """\
---
inclusion: always
---
# Technical Context

## Tech Stack
{tech_stack}

## Development Setup
- Install: `{install_cmd}`
- Dev server: `{dev_cmd}`
- Test: `{test_cmd}`
"""

KIRO_STRUCTURE_TEMPLATE = """\
---
inclusion: always
---
# Repository Structure

{architecture}

## File Conventions
<!-- Describe naming conventions, import patterns, etc. -->
"""

STOP_HOOK_REQUIRE_TESTS = """\
#!/bin/bash
# Stop hook: require tests to pass before Claude Code stops
if ! {test_cmd} >/dev/null 2>&1; then
  echo '{{"decision": "block", "reason": "Tests are failing. Fix test failures before stopping."}}'
else
  exit 0
fi
"""

POST_TOOL_USE_LINT = """\
#!/bin/bash
# PostToolUse hook: auto-lint after file edits
INPUT=$(cat /dev/stdin)
TOOL=$(echo "$INPUT" | jq -r '.tool_name')
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ "$TOOL" == "Write" || "$TOOL" == "Edit" ]] && [[ -n "$FILE" ]]; then
  {lint_cmd} "$FILE" --fix 2>/dev/null || true
fi
exit 0
"""

SETTINGS_HOOKS_TEMPLATE = """\
{{
  "hooks": {{
    "Stop": [
      {{
        "type": "command",
        "command": "bash .claude/hooks/require-tests.sh"
      }}
    ],
    "PostToolUse": [
      {{
        "type": "command",
        "command": "bash .claude/hooks/auto-lint.sh"
      }}
    ]
  }}
}}
"""

ARCHITECTURE_TEMPLATE = """\
# Architecture

> Generated by harness-kit. Fill in your project's actual architecture.

## Overview

<!-- High-level description of the system -->

## Layers / Modules

<!-- Describe the main modules and their responsibilities -->
<!-- Example:
- **UI Layer**: React components, pages, routing
- **Service Layer**: Business logic, API calls
- **Data Layer**: Database access, caching
-->

## Dependency Rules

<!-- Which layers can import from which? -->
<!-- Example: UI -> Service -> Data (never reverse) -->

## Key Design Decisions

| Decision | Rationale | Date |
|----------|-----------|------|
| <!-- e.g. "Use PostgreSQL" --> | <!-- e.g. "Team expertise + JSONB support" --> | <!-- date --> |
"""

# --- Project type presets -------------------------------------------------------

PRESETS: dict[str, dict[str, str]] = {
    "web-app": {
        "project_description": "A web application built with [framework].",
        "tech_stack": "[Next.js/React], [TypeScript], [PostgreSQL], [Tailwind CSS]",
        "install_cmd": "npm install",
        "dev_cmd": "npm run dev",
        "test_cmd": "npm test -- --watchAll=false",
        "lint_cmd": "npm run lint",
        "typecheck_cmd": "npx tsc --noEmit",
        "pkg_manager": "npm",
        "architecture": "```\nsrc/\n  components/   — UI components\n  pages/        — Route pages\n  services/     — Business logic\n  lib/          — Shared utilities\n  types/        — TypeScript types\n```",
    },
    "api-service": {
        "project_description": "A REST/GraphQL API service.",
        "tech_stack": "[Express/FastAPI], [TypeScript/Python], [PostgreSQL/DynamoDB]",
        "install_cmd": "npm install",
        "dev_cmd": "npm run dev",
        "test_cmd": "npm test -- --watchAll=false",
        "lint_cmd": "npm run lint",
        "typecheck_cmd": "npx tsc --noEmit",
        "pkg_manager": "npm",
        "architecture": "```\nsrc/\n  routes/       — API route handlers\n  services/     — Business logic\n  repositories/ — Database access\n  middleware/   — Auth, validation, logging\n  types/        — Type definitions\n```",
    },
    "cli-tool": {
        "project_description": "A command-line tool.",
        "tech_stack": "[Python/Rust/Go], [click/clap/cobra]",
        "install_cmd": "pip install -e '.[dev]'",
        "dev_cmd": "python -m my_tool",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "typecheck_cmd": "mypy .",
        "pkg_manager": "pip",
        "architecture": "```\nsrc/\n  cli.py        — CLI entry point\n  commands/     — Subcommands\n  core/         — Core logic\n  utils/        — Shared utilities\n```",
    },
    "data-pipeline": {
        "project_description": "A data processing pipeline.",
        "tech_stack": "Python, [Airflow/Prefect/Spark], [S3/BigQuery/Snowflake]",
        "install_cmd": "pip install -e '.[dev]'",
        "dev_cmd": "python -m pipeline --dry-run",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "typecheck_cmd": "mypy .",
        "pkg_manager": "pip",
        "architecture": "```\npipeline/\n  extractors/   — Data extraction\n  transformers/ — Data transformation\n  loaders/      — Data loading\n  schemas/      — Data schemas/validation\n  config/       — Pipeline configuration\n```",
    },
    "ml-project": {
        "project_description": "A machine learning project.",
        "tech_stack": "Python, [PyTorch/TensorFlow/scikit-learn], [MLflow/W&B]",
        "install_cmd": "pip install -e '.[dev]'",
        "dev_cmd": "python train.py --debug",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "typecheck_cmd": "mypy .",
        "pkg_manager": "pip",
        "architecture": "```\nsrc/\n  data/         — Data loading and preprocessing\n  models/       — Model definitions\n  training/     — Training loops\n  evaluation/   — Metrics and evaluation\n  inference/    — Prediction serving\n  configs/      — Experiment configs\n```",
    },
}

# --- Main logic -----------------------------------------------------------------


def run_init(
    target: str,
    tools: str | None,
    project_type: str | None,
    level: int | None,
    skip_existing: bool = False,
) -> None:
    """Run the init command."""
    target_path = Path(target).resolve()

    console.print(
        Panel.fit(
            "[bold]harness-kit init[/bold]\n"
            f"Target: {target_path}",
            border_style="blue",
        )
    )

    # Interactive prompts if not provided
    if tools is None:
        tools = Prompt.ask(
            "Which AI tools do you use?",
            choices=["claude-code", "kiro", "both"],
            default="both",
        )

    if project_type is None:
        project_type = Prompt.ask(
            "Project type?",
            choices=list(PRESETS.keys()),
            default="web-app",
        )

    if level is None:
        level = int(
            Prompt.ask(
                "Harness level? (1=rules, 2=+constraints, 3=full)",
                choices=["1", "2", "3"],
                default="2",
            )
        )

    preset = dict(PRESETS[project_type])  # copy so we can override
    use_claude = tools in ("claude-code", "both")
    use_kiro = tools in ("kiro", "both")

    # --- Auto-detect from existing project files ---
    detected = _detect_project(target_path)
    if detected:
        console.print(f"[dim]Detected: {', '.join(f'{k}={v}' for k, v in detected.items())}[/dim]")
        preset.update(detected)

    generated_files: list[str] = []

    def write(path: Path, content: str) -> None:
        _write_file(path, content, skip_existing=skip_existing)

    # --- Layer 1: Universal (always) ---
    write(target_path / "HARNESS.md", AGENTS_MD_STANDARD.format(**preset))
    generated_files.append("HARNESS.md")

    # --- Layer 2: Platform adapters ---
    if use_claude:
        write(target_path / "CLAUDE.md", CLAUDE_MD_TEMPLATE)
        generated_files.append("CLAUDE.md")

    if use_kiro:
        kiro_dir = target_path / ".kiro" / "steering"
        kiro_dir.mkdir(parents=True, exist_ok=True)
        write(kiro_dir / "product.md", KIRO_PRODUCT_TEMPLATE.format(**preset))
        write(kiro_dir / "tech.md", KIRO_TECH_TEMPLATE.format(**preset))
        write(kiro_dir / "structure.md", KIRO_STRUCTURE_TEMPLATE.format(**preset))
        generated_files.extend([
            ".kiro/steering/product.md",
            ".kiro/steering/tech.md",
            ".kiro/steering/structure.md",
        ])

    # --- Layer 2+: Knowledge base (level >= 1) ---
    docs_dir = target_path / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    write(docs_dir / "ARCHITECTURE.md", ARCHITECTURE_TEMPLATE)
    generated_files.append("docs/ARCHITECTURE.md")

    # --- Layer 3: Hooks + constraints (level >= 2) ---
    if level >= 2 and use_claude:
        hooks_dir = target_path / ".claude" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        write(
            hooks_dir / "require-tests.sh",
            STOP_HOOK_REQUIRE_TESTS.format(**preset),
        )
        write(
            hooks_dir / "auto-lint.sh",
            POST_TOOL_USE_LINT.format(**preset),
        )
        # Make hooks executable
        (hooks_dir / "require-tests.sh").chmod(0o755)
        (hooks_dir / "auto-lint.sh").chmod(0o755)

        generated_files.extend([
            ".claude/hooks/require-tests.sh",
            ".claude/hooks/auto-lint.sh",
        ])

    # --- Layer 3: Full harness (level 3) ---
    if level >= 3 and use_claude:
        settings_dir = target_path / ".claude"
        settings_dir.mkdir(parents=True, exist_ok=True)
        write(settings_dir / "settings.json", SETTINGS_HOOKS_TEMPLATE)
        generated_files.append(".claude/settings.json")

    # --- Summary ---
    console.print()
    console.print(f"[bold green]Generated {len(generated_files)} files:[/bold green]")
    for f in generated_files:
        console.print(f"  [dim]{f}[/dim]")

    console.print()
    console.print(
        Panel.fit(
            "[bold]Next steps:[/bold]\n"
            "1. Edit HARNESS.md — replace placeholders with your project's real info\n"
            "2. Start using your AI tool — observe where the agent makes mistakes\n"
            "3. Add one line to HARNESS.md per mistake — this is error-driven writing\n"
            "4. Run [bold]harness-kit score[/bold] periodically to track your maturity",
            border_style="green",
        )
    )


def _write_file(path: Path, content: str, skip_existing: bool = False) -> None:
    """Write a file, skipping if it already exists."""
    if path.exists():
        if skip_existing:
            console.print(f"  [yellow]Skipped[/yellow] {path.name} (already exists)")
            return
        if not Confirm.ask(f"  {path.name} already exists. Overwrite?", default=False):
            console.print(f"  [yellow]Skipped[/yellow] {path.name}")
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    console.print(f"  [green]Created[/green] {path.relative_to(path.parent.parent) if len(path.parts) > 2 else path.name}")


def _detect_project(target: Path) -> dict[str, str]:
    """Auto-detect project tech stack from existing files."""
    detected: dict[str, str] = {}

    # Detect from pyproject.toml
    pyproject = target / "pyproject.toml"
    if pyproject.exists():
        content = pyproject.read_text()
        # Extract project name and description
        import re
        name_match = re.search(r'^name\s*=\s*"([^"]+)"', content, re.MULTILINE)
        desc_match = re.search(r'^description\s*=\s*"([^"]+)"', content, re.MULTILINE)
        if name_match and desc_match:
            detected["project_description"] = f"{name_match.group(1)}: {desc_match.group(1)}"
        elif desc_match:
            detected["project_description"] = desc_match.group(1)

        # Detect Python deps for tech stack
        deps: list[str] = []
        deps.append("Python")
        if "fastapi" in content.lower():
            deps.append("FastAPI")
        if "django" in content.lower():
            deps.append("Django")
        if "flask" in content.lower():
            deps.append("Flask")
        if "click" in content.lower():
            deps.append("click")
        if "boto3" in content.lower():
            deps.append("AWS SDK (boto3)")
        if "pytorch" in content.lower() or "torch" in content.lower():
            deps.append("PyTorch")
        if "tensorflow" in content.lower():
            deps.append("TensorFlow")
        if "strands" in content.lower():
            deps.append("Strands Agents")
        if "bedrock" in content.lower():
            deps.append("Amazon Bedrock")
        if deps:
            detected["tech_stack"] = ", ".join(deps)

        detected["install_cmd"] = "pip install -e '.[dev]'"
        detected["dev_cmd"] = f"python -m {name_match.group(1).replace('-', '_')}" if name_match else "python -m app"
        detected["test_cmd"] = "pytest"
        detected["lint_cmd"] = "ruff check ."
        detected["typecheck_cmd"] = "mypy ."
        detected["pkg_manager"] = "pip"

        # Check if ruff is configured
        if "ruff" not in content and not (target / "ruff.toml").exists():
            detected["lint_cmd"] = "flake8 ."

    # Detect from package.json
    pkg_json = target / "package.json"
    if pkg_json.exists():
        import json
        try:
            pkg = json.loads(pkg_json.read_text())
            if "name" in pkg and "description" in pkg:
                detected["project_description"] = f"{pkg['name']}: {pkg.get('description', '')}"
            elif "name" in pkg:
                detected["project_description"] = pkg["name"]

            deps_list: list[str] = []
            all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "next" in all_deps:
                deps_list.append("Next.js")
            if "react" in all_deps:
                deps_list.append("React")
            if "vue" in all_deps:
                deps_list.append("Vue")
            if "express" in all_deps:
                deps_list.append("Express")
            if "typescript" in all_deps:
                deps_list.append("TypeScript")
            if "prisma" in all_deps or "@prisma/client" in all_deps:
                deps_list.append("Prisma")
            if "tailwindcss" in all_deps:
                deps_list.append("Tailwind CSS")
            if deps_list:
                detected["tech_stack"] = ", ".join(deps_list)

            # Detect package manager
            if (target / "pnpm-lock.yaml").exists():
                detected["pkg_manager"] = "pnpm"
                detected["install_cmd"] = "pnpm install"
                detected["dev_cmd"] = "pnpm dev"
                detected["test_cmd"] = "pnpm test -- --watchAll=false"
                detected["lint_cmd"] = "pnpm lint"
            elif (target / "yarn.lock").exists():
                detected["pkg_manager"] = "yarn"
                detected["install_cmd"] = "yarn install"
                detected["dev_cmd"] = "yarn dev"
                detected["test_cmd"] = "yarn test --watchAll=false"
                detected["lint_cmd"] = "yarn lint"
            else:
                detected["pkg_manager"] = "npm"
                detected["install_cmd"] = "npm install"
                detected["dev_cmd"] = "npm run dev"
                detected["test_cmd"] = "npm test -- --watchAll=false"
                detected["lint_cmd"] = "npm run lint"

            detected["typecheck_cmd"] = "npx tsc --noEmit" if "typescript" in all_deps else "# no type checker"

            # Detect scripts
            scripts = pkg.get("scripts", {})
            if "test" in scripts:
                base = detected.get("pkg_manager", "npm")
                if base == "npm":
                    detected["test_cmd"] = "npm test -- --watchAll=false"
                else:
                    detected["test_cmd"] = f"{base} test --watchAll=false"
        except (json.JSONDecodeError, KeyError):
            pass

    # Detect directory structure for architecture
    src_dirs: list[str] = []
    # First try common source directories
    for candidate in ["src", "app", "lib", "pkg", "cmd", "internal"]:
        candidate_path = target / candidate
        if candidate_path.is_dir():
            subdirs = [d.name for d in sorted(candidate_path.iterdir()) if d.is_dir() and not d.name.startswith((".", "_"))]
            if subdirs:
                lines = [f"{candidate}/"]
                for sd in subdirs[:10]:
                    lines.append(f"  {sd}/")
                src_dirs.extend(lines)

    # If no src/ found, scan root-level directories (Python projects often use flat layout)
    if not src_dirs:
        skip = {".git", ".venv", "venv", ".idea", ".vscode", "node_modules", "__pycache__",
                ".kiro", ".claude", "docs", "logs", ".github", "backups", ".eggs", "dist", "build"}
        root_dirs = [
            d.name for d in sorted(target.iterdir())
            if d.is_dir() and d.name not in skip and not d.name.startswith(".")
        ]
        if root_dirs:
            for rd in root_dirs[:12]:
                src_dirs.append(f"{rd}/")

    if src_dirs:
        detected["architecture"] = "```\n" + "\n".join(src_dirs) + "\n```"

    return detected
